### ISSUE TITLE
Version 3.5.2 (25235) "Export This Page" not working

### ISSUE THREAD

**Issue by anthonyina** [andrewfiorillo/sketch-artboards-to-pdf#1]
Export all pages works, but this is no different then what Sketch does already. If it put them in order from left > right top > bottom, even that would be an improvement.

**Comment by andrewfiorillo** [comment]
Yeah, the only difference from the built-in functionality is that you can export from a single page. While working on a presentation recently, I found myself wanting to have multiple pages for different versions and revisions. This is a small script to do just that (at least for now).

I just pushed an update which should fix single page exporting. Let me know if you have any issues.
