### ISSUE TITLE
Export selected pages

### ISSUE THREAD

**Issue by tomcole** [andrewfiorillo/sketch-artboards-to-pdf#16]
Great plugin, thanks! It would be great if you could export all the artboards in your selected pages (Sketch now supports multiple selection of pages in the sidebar). Is that possible?

**Comment by AlexandraLouise** [comment]
Hi @andrewfiorillo I see that this is an option in the plugins menu, but when I try to select it it says "No Artboards Selected"

**Comment by andrewfiorillo** [comment]
I just pushed a [change](https://github.com/andrewfiorillo/sketch-artboards-to-pdf/commit/1e6a316f67fae522abab84ee980652feacb94eb9) that adds this functionality. Let me know if it doesn't work. Thanks!
