### ISSUE TITLE
Export current page no longer working

### ISSUE THREAD

**Issue by sgraden** [andrewfiorillo/sketch-artboards-to-pdf#6]
Version 39.1 

Nothing happens after selecting "Export current page"

**Comment by andrewfiorillo** [comment]
I just checked it out, and I haven't been able to reproduce the bug.

There was a change I pushed which fixed a bug introduced by a recent Sketch update. If you haven't yet, try grabbing the latest version of the plugin and see if that works.

**Comment by sgraden** [comment]
Will do. Usually the save location screen should pop up right?

**Comment by andrewfiorillo** [comment]
Yeah
