### ISSUE TITLE
Multiple shadows do not export properly

### ISSUE THREAD

**Issue by trhaynes** [andrewfiorillo/sketch-artboards-to-pdf#8]
Sketch:

![image](https://cloud.githubusercontent.com/assets/294560/20220843/1a5ea612-a7fd-11e6-80b0-f500414dabb7.png)

Exported:

![image](https://cloud.githubusercontent.com/assets/294560/20220862/2b599530-a7fd-11e6-9ac4-439249793477.png)

It looks like the first shadow was not exported, only the second one.

Sketch file and PDF: [example.zip](https://github.com/andrewfiorillo/sketch-artboards-to-pdf/files/586172/example.zip)

**Comment by andrewfiorillo** [comment]
I'm able to reproduce this, but it appears to be a bug in Sketch itself. If you export the document using the built in pdf export, it has the same issue.
